version: '3.8'

services:
  threads:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  mongo-orders:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-orders:/data/db

volumes:
  mongo-orders: